version: 0.2
phases:
  install:
    commands:
      - echo Installing Dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build -- --prod
artifacts:
  files:
    - "dist/frontend/**/*"
