version: 0.2

phases:
  install:
    commands:
      - npm install -g @angular/cli
  build:
    commands:
      - ng build --prod
  post_build:
    commands:
      - aws s3 cp dist/my-app s3://my-bucket/

artifacts:
  files:
    - dist/my-app/**/*
